name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'hello world from CI'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: testy_mc_face
          postgresql password: hacked123

      - name: Test everything
        run: PGDATABASE=test_db PGUSER=testy_mc_face PAPASSWORD=hacked123 npm t
